export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";

export const SOLANA_ADDRESS = "SOLANA_ADDRESS";
export const SOLANA_ADDRESS_SUCCESS = "SOLANA_ADDRESS_SUCCESS";
